server:
  port: 4500

spring:
  datasource:
    url: jdbc:h2:mem:coursedb

  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      ddl-auto: update

  liquibase:
    enabled: false
